apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-service
  namespace: argocd
  annotations:
    # Wave 2 chạy sau postgres để giảm lỗi khởi động do thiếu dependency.
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform
  source:
    repoURL: https://github.com/vanphutin/vanphutin-aws-accelerator-p2.git
    targetRevision: main
    path: cloud/w9/day-a/workloads/api-service
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
